# Generated by Django 4.2.7 on 2023-11-10 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0003_alter_review_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="updated_at",
        ),
    ]
