# Generated by Django 4.2.7 on 2023-11-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0004_remove_review_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
