# Generated by Django 4.2.7 on 2023-11-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0006_remove_review_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(),
        ),
    ]
